/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flink.bug;

import org.apache.flink.api.common.functions.ReduceFunction;
import org.apache.flink.api.java.functions.KeySelector;
import org.apache.flink.streaming.api.environment.LocalStreamEnvironment;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.streaming.api.windowing.assigners.ProcessingTimeSessionWindows;
import org.apache.flink.streaming.api.windowing.time.Time;
import org.apache.flink.streaming.api.windowing.triggers.ContinuousProcessingTimeTrigger;

/**
 * This will manage to cause a NPE in the ContinuousProcessingTimeTrigger#clear method:

 Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
   at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
   at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:647)
   at org.apache.flink.streaming.api.environment.LocalStreamEnvironment.execute(LocalStreamEnvironment.java:123)
   at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1510)
   at flink.bug.App.main(App.java:39)
 Caused by: java.lang.NullPointerException
   at org.apache.flink.streaming.api.windowing.triggers.ContinuousProcessingTimeTrigger.clear(ContinuousProcessingTimeTrigger.java:89)
   at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator$Context.clear(WindowOperator.java:912)
   at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator$2.merge(WindowOperator.java:336)
   at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator$2.merge(WindowOperator.java:311)
   at org.apache.flink.streaming.runtime.operators.windowing.MergingWindowSet.addWindow(MergingWindowSet.java:212)
   at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.processElement(WindowOperator.java:311)
   at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:202)
   at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:105)
   at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
   at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)
   at java.lang.Thread.run(Thread.java:748)

 */
public class Bug1 {
  public static void main(String[] args) throws Exception {
    LocalStreamEnvironment env = StreamExecutionEnvironment.createLocalEnvironment();
    env.setParallelism(1);

    env.addSource(new FakeSource())
        .keyBy(new KeySelector<String, String>() {
          @Override
          public String getKey(String value) throws Exception {
            return String.valueOf(value.charAt(0));
          }
        })
        .windowAll(ProcessingTimeSessionWindows.withGap(Time.seconds(1)))
        .trigger(ContinuousProcessingTimeTrigger.of(Time.seconds(5)))
        .reduce(new ReduceFunction<String>() {
          @Override
          public String reduce(String value1, String value2) throws Exception {
            return value1;
          }
        })
        .print();

    env.execute();
  }
}
