/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flink.bug;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Bug1 classUnderTest = new Bug1();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
